apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-networkpolicy
spec:
  podSelector:
    matchLabels:
      app: myapp-pod
  ingress:
    - from:
       - podSelector:
           matchLabels:
             access: "true"
