apiVersion: v1
kind: Service
metadata:
  name: my-service-np
  labels:
    app: myapp-service-np
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: myapp-pod
  type: NodePort