apiVersion: v1
kind: Service
metadata:
  name: my-service-lb
  labels:
    app: myapp-service-lb
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: myapp-pod
  type: LoadBalancer