apiVersion: v1
kind: Pod
metadata:
  name: mytest-pod
  labels:
    access: "true"
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']